

clear;
clc;
close all;

fprintf("SINGLE-FEATURE RF-LOSO TRANSFERABILITY\n");
fprintf("======================================\n\n");


scriptFile = mfilename("fullpath");

if strlength(scriptFile) == 0
    scriptFolder = string(pwd);
else
    scriptFolder = string(fileparts(scriptFile));
end

datasetFile = fullfile(scriptFolder, "capgmyo_ml_dataset.mat");

if ~isfile(datasetFile)
    fprintf("The dataset was not found beside this script.\n");
    fprintf("Select capgmyo_ml_dataset.mat manually.\n\n");

    [selectedFile, selectedFolder] = uigetfile( ...
        "*.mat", ...
        "Select capgmyo_ml_dataset.mat");

    if isequal(selectedFile,0)
        error("No dataset was selected.");
    end

    datasetFile = fullfile(selectedFolder, selectedFile);
end

resultsFolder = fullfile(scriptFolder, ...
    "single_feature_rf_loso_results");

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

progressFile = fullfile(resultsFolder, ...
    "single_feature_rf_loso_progress.mat");

numberOfTrees = 50;
minimumLeafSize = 5;
maximumSplits = 500;
randomSeedBase = 41000;

fprintf("LOCKED SETTINGS\n");
fprintf("---------------\n");
fprintf("Trees: %d\n", numberOfTrees);
fprintf("Minimum leaf size: %d\n", minimumLeafSize);
fprintf("Maximum splits: %d\n", maximumSplits);
fprintf("Class prior: uniform\n");
fprintf("Primary outcome: balanced accuracy\n\n");

fprintf("Loading dataset...\n");
D = load(datasetFile);

requiredDatasetVariables = [ ...
    "X", "Y", "subjectID", "featureNames", ...
    "predictorInformation" ...
    ];

loadedNames = string(fieldnames(D));

if ~all(ismember(requiredDatasetVariables, loadedNames))
    error("The selected file is missing required dataset variables.");
end

X = D.X;
Y = double(D.Y(:));
subjectID = double(D.subjectID(:));
featureNames = string(D.featureNames(:));
predictorInformation = D.predictorInformation;

subjects = unique(subjectID(:))';
classOrder = unique(Y(:))';
numberOfSubjects = numel(subjects);
numberOfClasses = numel(classOrder);
numberOfFeatures = numel(featureNames);
numberOfPredictors = size(X,2);

if numberOfSubjects ~= 18
    error("Expected 18 subjects but found %d.", numberOfSubjects);
end

if numberOfClasses ~= 8
    error("Expected 8 gesture classes but found %d.", numberOfClasses);
end

if numberOfFeatures ~= 21
    error("Expected 21 feature types but found %d.", numberOfFeatures);
end

if numberOfPredictors ~= 2688
    error("Expected 2688 predictors but found %d.", numberOfPredictors);
end

predictorFeatureNumber = double( ...
    predictorInformation.FeatureNumber(:));

for featureNumber = 1:numberOfFeatures
    predictorCount = sum(predictorFeatureNumber == featureNumber);

    if predictorCount ~= 128
        error("Feature %d has %d predictors; expected 128.", ...
            featureNumber, predictorCount);
    end
end

fprintf("Observations: %d\n", size(X,1));
fprintf("Subjects: %d\n", numberOfSubjects);
fprintf("Gestures: %d\n", numberOfClasses);
fprintf("Feature types: %d\n", numberOfFeatures);
fprintf("Predictors retained per feature: 128\n\n");

balancedAccuracy = nan(numberOfFeatures, numberOfSubjects);
ordinaryAccuracy = nan(numberOfFeatures, numberOfSubjects);
trainingTimeSeconds = nan(numberOfFeatures, numberOfSubjects);
predictionTimeSeconds = nan(numberOfFeatures, numberOfSubjects);
completed = false(numberOfFeatures, numberOfSubjects);

if isfile(progressFile)
    fprintf("Existing progress file found. Validating it...\n");
    P = load(progressFile);

    requiredProgressVariables = [ ...
        "balancedAccuracy", ...
        "ordinaryAccuracy", ...
        "trainingTimeSeconds", ...
        "predictionTimeSeconds", ...
        "completed", ...
        "numberOfTreesUsed", ...
        "minimumLeafSizeUsed", ...
        "maximumSplitsUsed" ...
        ];

    progressNames = string(fieldnames(P));

    if ~all(ismember(requiredProgressVariables, progressNames))
        error([ ...
            "The existing progress file is incomplete. " ...
            "Move it out of the results folder and rerun." ...
            ]);
    end

    settingsMatch = ...
        P.numberOfTreesUsed == numberOfTrees && ...
        P.minimumLeafSizeUsed == minimumLeafSize && ...
        P.maximumSplitsUsed == maximumSplits;

    dimensionsMatch = ...
        isequal(size(P.balancedAccuracy), ...
        [numberOfFeatures numberOfSubjects]);

    if ~settingsMatch || ~dimensionsMatch
        error([ ...
            "The progress file was created with different settings or " ...
            "dataset dimensions. Do not mix analyses." ...
            ]);
    end

    balancedAccuracy = P.balancedAccuracy;
    ordinaryAccuracy = P.ordinaryAccuracy;
    trainingTimeSeconds = P.trainingTimeSeconds;
    predictionTimeSeconds = P.predictionTimeSeconds;
    completed = P.completed;

    fprintf("Resuming with %d of %d folds already complete.\n\n", ...
        nnz(completed), numel(completed));
end

totalFolds = numberOfFeatures * numberOfSubjects;

for featureNumber = 1:numberOfFeatures

    predictorMask = predictorFeatureNumber == featureNumber;
    XFeature = X(:,predictorMask);

    fprintf("FEATURE %d OF %d: %s\n", ...
        featureNumber, numberOfFeatures, featureNames(featureNumber));
    fprintf("----------------------------------------\n");

    for subjectPosition = 1:numberOfSubjects

        foldNumber = ...
            (featureNumber-1)*numberOfSubjects + subjectPosition;
        heldSubject = subjects(subjectPosition);

        if completed(featureNumber,subjectPosition)
            fprintf("Fold %d/%d, subject %d: checkpoint found; skipped.\n", ...
                foldNumber, totalFolds, heldSubject);
            continue;
        end

        rng(randomSeedBase + 100*featureNumber + heldSubject, ...
            "twister");

        trainMask = subjectID ~= heldSubject;
        testMask = subjectID == heldSubject;

        XTrain = XFeature(trainMask,:);
        YTrain = Y(trainMask);
        XTest = XFeature(testMask,:);
        YTest = Y(testMask);

        variablesPerSplit = floor(sqrt(size(XFeature,2)));

        treeLearner = templateTree( ...
            "NumVariablesToSample", variablesPerSplit, ...
            "MinLeafSize", minimumLeafSize, ...
            "MaxNumSplits", maximumSplits);

        fprintf("Fold %d/%d, holding out subject %d...\n", ...
            foldNumber, totalFolds, heldSubject);

        trainingTimer = tic;

        model = fitcensemble( ...
            XTrain, ...
            YTrain, ...
            "Method", "Bag", ...
            "NumLearningCycles", numberOfTrees, ...
            "Learners", treeLearner, ...
            "Prior", "uniform", ...
            "ClassNames", classOrder);

        trainingTimeSeconds(featureNumber,subjectPosition) = ...
            toc(trainingTimer);

        predictionTimer = tic;
        prediction = predict(model, XTest);
        predictionTimeSeconds(featureNumber,subjectPosition) = ...
            toc(predictionTimer);

        ordinaryAccuracy(featureNumber,subjectPosition) = ...
            mean(prediction == YTest);

        classRecall = nan(numberOfClasses,1);

        for classPosition = 1:numberOfClasses
            gesture = classOrder(classPosition);
            gestureMask = YTest == gesture;

            classRecall(classPosition) = mean( ...
                prediction(gestureMask) == gesture);
        end

        balancedAccuracy(featureNumber,subjectPosition) = ...
            mean(classRecall, "omitnan");

        completed(featureNumber,subjectPosition) = true;

        fprintf("Balanced accuracy: %.2f%% | Training: %.2f s\n", ...
            100*balancedAccuracy(featureNumber,subjectPosition), ...
            trainingTimeSeconds(featureNumber,subjectPosition));

        % Save after every fold so interruption loses at most one fold.
        numberOfTreesUsed = numberOfTrees;
        minimumLeafSizeUsed = minimumLeafSize;
        maximumSplitsUsed = maximumSplits;

        save(progressFile, ...
            "balancedAccuracy", ...
            "ordinaryAccuracy", ...
            "trainingTimeSeconds", ...
            "predictionTimeSeconds", ...
            "completed", ...
            "numberOfTreesUsed", ...
            "minimumLeafSizeUsed", ...
            "maximumSplitsUsed", ...
            "featureNames", ...
            "subjects", ...
            "classOrder");

        clear model XTrain XTest YTrain YTest prediction
    end

    fprintf("\n");
end

if ~all(completed,"all")
    error("Not all folds are complete. Rerun this script to resume.");
end

meanBalancedAccuracy = mean( ...
    balancedAccuracy, 2, "omitnan");

sdBalancedAccuracy = std( ...
    balancedAccuracy, 0, 2, "omitnan");

medianBalancedAccuracy = median( ...
    balancedAccuracy, 2, "omitnan");

minimumBalancedAccuracy = min( ...
    balancedAccuracy, [], 2, "omitnan");

maximumBalancedAccuracy = max( ...
    balancedAccuracy, [], 2, "omitnan");

[sortedMeanAccuracy, featureOrder] = sort( ...
    meanBalancedAccuracy, "descend");

transferabilityRanking = table( ...
    (1:numberOfFeatures)', ...
    featureOrder, ...
    featureNames(featureOrder), ...
    100*sortedMeanAccuracy, ...
    100*sdBalancedAccuracy(featureOrder), ...
    100*medianBalancedAccuracy(featureOrder), ...
    100*minimumBalancedAccuracy(featureOrder), ...
    100*maximumBalancedAccuracy(featureOrder), ...
    'VariableNames', ...
    { ...
    'Rank', ...
    'FeatureNumber', ...
    'FeatureName', ...
    'MeanBalancedAccuracyPercent', ...
    'SDBalancedAccuracyPercent', ...
    'MedianBalancedAccuracyPercent', ...
    'MinimumSubjectAccuracyPercent', ...
    'MaximumSubjectAccuracyPercent' ...
    });

fprintf("SINGLE-FEATURE RF-LOSO RANKING\n");
fprintf("==============================\n");
disp(transferabilityRanking);

subjectVariableNames = compose("Subject_%02d", subjects);

accuracyBySubjectTable = array2table( ...
    100*balancedAccuracy, ...
    "VariableNames", subjectVariableNames);

accuracyBySubjectTable = addvars( ...
    accuracyBySubjectTable, ...
    (1:numberOfFeatures)', ...
    featureNames, ...
    'Before', 1, ...
    'NewVariableNames', {'FeatureNumber','FeatureName'});

finalResultsFile = fullfile(resultsFolder, ...
    "single_feature_rf_loso_final.mat");

save(finalResultsFile, ...
    "balancedAccuracy", ...
    "ordinaryAccuracy", ...
    "trainingTimeSeconds", ...
    "predictionTimeSeconds", ...
    "meanBalancedAccuracy", ...
    "sdBalancedAccuracy", ...
    "medianBalancedAccuracy", ...
    "transferabilityRanking", ...
    "accuracyBySubjectTable", ...
    "featureNames", ...
    "subjects", ...
    "numberOfTrees", ...
    "minimumLeafSize", ...
    "maximumSplits");

writetable(transferabilityRanking, fullfile(resultsFolder, ...
    "single_feature_rf_loso_ranking.csv"));

writetable(accuracyBySubjectTable, fullfile(resultsFolder, ...
    "single_feature_rf_loso_by_subject.csv"));

figureHandle = figure( ...
    "Color", "white", ...
    "Name", "Single-Feature RF-LOSO Transferability");

barh(100*sortedMeanAccuracy, ...
    "FaceColor", [0.20 0.60 0.45]);
hold on;

errorbar( ...
    100*sortedMeanAccuracy, ...
    1:numberOfFeatures, ...
    100*sdBalancedAccuracy(featureOrder), ...
    "horizontal", ...
    "LineStyle", "none", ...
    "Color", [0.15 0.15 0.15], ...
    "CapSize", 4);

xline(100/numberOfClasses, "--", ...
    "Chance (12.5%)", ...
    "Color", [0.65 0.15 0.15], ...
    "LabelVerticalAlignment", "bottom");

yticks(1:numberOfFeatures);
yticklabels(featureNames(featureOrder));
set(gca, "YDir", "reverse");
xlabel("Mean LOSO balanced accuracy (%)");
ylabel("Feature used alone across 128 channels");
title("Cross-User Transferability of Individual EMG Features");
grid on;

figureFile = fullfile(resultsFolder, ...
    "single_feature_rf_loso_ranking.png");

exportgraphics(figureHandle, figureFile, "Resolution", 300);

fprintf("\nANALYSIS COMPLETE\n");
fprintf("=================\n");
fprintf("Final results:\n%s\n", finalResultsFile);
fprintf("Results folder:\n%s\n", resultsFolder);

